### ISSUE TITLE
"NoneType" of disabled lower bound

### ISSUE THREAD

**Issue by VladislavAksiotis** [bioelectric-interfaces/nfb_studio#6]
I unchecked the Lower Bound configuration in the signal property, saved the setting as an xml file, imported it and got the error.

```
Traceback (most recent call last):
  File "c:\users\владислав\nfb_studio\nfb_studio\experiment_view.py", line 510, in actionImport
    ex = Experiment.import_xml(data)
  File "c:\users\владислав\nfb_studio\nfb_studio\experiment.py", line 198, in import_xml
    n.setLowerBound(float(signal_data.get("fBandpassLowHz", n.default_lower_bound)))
TypeError: float() argument must be a string or a number, not 'NoneType'
```

![Setting](https://user-images.githubusercontent.com/60115817/111878243-7f708380-89b8-11eb-8287-afc5ed836850.jpeg)

**Comment by andreasxp** [comment]
Fixed in master.
